In [1]:
import pandas as pd

In [2]:
npr = pd.read_csv('./05-Topic-Modeling/npr.csv')
npr.head()

Article
0  In the Washington of 2016, even when the polic...
1    Donald Trump has used Twitter  —   his prefe...
2    Donald Trump is unabashedly praising Russian...
3  Updated at 2:50 p. m. ET, Russian President Vl...
4  From photography, illustration and video, to d...

In [6]:
len(npr.iloc[0]['Article'])    # len(npr['Article'][0])

7646

In [7]:
len(npr)

11992

In [9]:
from sklearn.feature_extraction.text import CountVectorizer

cv = CountVectorizer(max_df=0.9,min_df=2,stop_words='english')

In [10]:
dtm = cv.fit_transform(npr['Article'])
dtm

<11992x54777 sparse matrix of type '<class 'numpy.int64'>'
	with 3033388 stored elements in Compressed Sparse Row format>

In [11]:
from sklearn.decomposition import LatentDirichletAllocation

LDA = LatentDirichletAllocation(n_components=7,random_state=42)

LDA.fit(dtm)

LatentDirichletAllocation(n_components=7, random_state=42)

In [16]:
len(cv.get_feature_names_out())

54777

In [22]:
cv.get_feature_names_out()[6000]

'blake'

In [23]:
len(LDA.components_)

7

In [25]:
LDA.components_.shape

(7, 54777)

In [26]:
LDA.components_

array([[8.64332806e+00, 2.38014333e+03, 1.42900522e-01, ...,
        1.43006821e-01, 1.42902042e-01, 1.42861626e-01],
       [2.76191749e+01, 5.36394437e+02, 1.42857148e-01, ...,
        1.42861973e-01, 1.42857147e-01, 1.42906875e-01],
       [7.22783888e+00, 8.24033986e+02, 1.42857148e-01, ...,
        6.14236247e+00, 2.14061364e+00, 1.42923753e-01],
       ...,
       [3.11488651e+00, 3.50409655e+02, 1.42857147e-01, ...,
        1.42859912e-01, 1.42857146e-01, 1.42866614e-01],
       [4.61486388e+01, 5.14408600e+01, 3.14281373e+00, ...,
        1.43107628e-01, 1.43902481e-01, 2.14271779e+00],
       [4.93991422e-01, 4.18841042e+02, 1.42857151e-01, ...,
        1.42857146e-01, 1.43760101e-01, 1.42866201e-01]])

In [27]:
single_topic = LDA.components_[0]

In [28]:
single_topic.argsort()

array([ 2475, 18302, 35285, ..., 22673, 42561, 42993])

In [30]:
single_topic.argsort()[-10:]

array([33390, 36310, 21228, 10425, 31464,  8149, 36283, 22673, 42561,
       42993])

In [32]:
top_ten_words = single_topic.argsort()[-10:]

In [33]:
for i in top_ten_words:
    print(cv.get_feature_names_out()[i])

new
percent
government
company
million
care
people
health
said
says


In [36]:
for i,topic in enumerate(LDA.components_):
    print(f'Top 15 words for topic {i+1}')
    print([cv.get_feature_names_out()[index] for index in topic.argsort()[-15:]])
    print('\n')

Top 15 words for topic 1
['companies', 'money', 'year', 'federal', '000', 'new', 'percent', 'government', 'company', 'million', 'care', 'people', 'health', 'said', 'says']


Top 15 words for topic 2
['military', 'house', 'security', 'russia', 'government', 'npr', 'reports', 'says', 'news', 'people', 'told', 'police', 'president', 'trump', 'said']


Top 15 words for topic 3
['way', 'world', 'family', 'home', 'day', 'time', 'water', 'city', 'new', 'years', 'food', 'just', 'people', 'like', 'says']


Top 15 words for topic 4
['time', 'new', 'don', 'years', 'medical', 'disease', 'patients', 'just', 'children', 'study', 'like', 'women', 'health', 'people', 'says']


Top 15 words for topic 5
['voters', 'vote', 'election', 'party', 'new', 'obama', 'court', 'republican', 'campaign', 'people', 'state', 'president', 'clinton', 'said', 'trump']


Top 15 words for topic 6
['years', 'going', 've', 'life', 'don', 'new', 'way', 'music', 'really', 'time', 'know', 'think', 'people', 'just', 'like']


T

In [37]:
topic_results = LDA.transform(dtm)

In [40]:
len(topic_results)

11992

In [43]:
topic_results[0]

array([1.61040465e-02, 6.83341493e-01, 2.25376318e-04, 2.25369288e-04,
       2.99652737e-01, 2.25479379e-04, 2.25497980e-04])

In [44]:
topic_results[0].round(2)

array([0.02, 0.68, 0.  , 0.  , 0.3 , 0.  , 0.  ])

In [46]:
topic_results[0].argmax()

1

In [47]:
npr['Topic'] = topic_results.argmax(axis=1)

In [48]:
npr.head()

Article  Topic
0  In the Washington of 2016, even when the polic...      1
1    Donald Trump has used Twitter  —   his prefe...      1
2    Donald Trump is unabashedly praising Russian...      1
3  Updated at 2:50 p. m. ET, Russian President Vl...      1
4  From photography, illustration and video, to d...      2

In [49]:
import pandas as pd

npr = pd.read_csv('./05-Topic-Modeling/npr.csv')

npr.head()

Article
0  In the Washington of 2016, even when the polic...
1    Donald Trump has used Twitter  —   his prefe...
2    Donald Trump is unabashedly praising Russian...
3  Updated at 2:50 p. m. ET, Russian President Vl...
4  From photography, illustration and video, to d...

In [50]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [51]:
tfidf = TfidfVectorizer(max_df=0.95,min_df=2,stop_words='english')

In [52]:
dtm = tfidf.fit_transform(npr['Article'])

In [53]:
dtm

<11992x54777 sparse matrix of type '<class 'numpy.float64'>'
	with 3033388 stored elements in Compressed Sparse Row format>

In [54]:
from sklearn.decomposition import NMF

In [55]:
nmf_model = NMF(n_components=7,random_state=42)

In [56]:
nmf_model.fit(dtm)

NMF(n_components=7, random_state=42)

In [58]:
for i,topic in enumerate(nmf_model.components_):
    print(f'Top 15 words for topic {i}')
    print([tfidf.get_feature_names_out()[index] for index in topic.argsort()[-15:]])
    print('\n')

Top 15 words for topic 0
['new', 'research', 'like', 'patients', 'health', 'disease', 'percent', 'women', 'virus', 'study', 'water', 'food', 'people', 'zika', 'says']


Top 15 words for topic 1
['gop', 'pence', 'presidential', 'russia', 'administration', 'election', 'republican', 'obama', 'white', 'house', 'donald', 'campaign', 'said', 'president', 'trump']


Top 15 words for topic 2
['senate', 'house', 'people', 'act', 'law', 'tax', 'plan', 'republicans', 'affordable', 'obamacare', 'coverage', 'medicaid', 'insurance', 'care', 'health']


Top 15 words for topic 3
['officers', 'syria', 'security', 'department', 'law', 'isis', 'russia', 'government', 'state', 'attack', 'president', 'reports', 'court', 'said', 'police']


Top 15 words for topic 4
['primary', 'cruz', 'election', 'democrats', 'percent', 'party', 'delegates', 'vote', 'state', 'democratic', 'hillary', 'campaign', 'voters', 'sanders', 'clinton']


Top 15 words for topic 5
['love', 've', 'don', 'album', 'way', 'time', 'song', '

In [59]:
topic_results = nmf_model.transform(dtm)

In [61]:
npr['Topic'] = topic_results.argmax(axis=1)

In [62]:
npr.head()

Article  Topic
0  In the Washington of 2016, even when the polic...      1
1    Donald Trump has used Twitter  —   his prefe...      1
2    Donald Trump is unabashedly praising Russian...      1
3  Updated at 2:50 p. m. ET, Russian President Vl...      3
4  From photography, illustration and video, to d...      6